// Mock data for development when backend is not available

export const mockSubscriptionPlans = [
  {
    id: '1',
    name: 'Free',
    price: '0',
    yearlyPrice: '0',
    billingCycle: 'MONTHLY' as const,
    features: {
      maxRecipeGenerations: 5,
      maxVideoGenerations: 1,
      maxCommunityPosts: 3,
      maxCommunityComments: 10,
      premiumTemplates: false,
      aiSuggestions: false,
      prioritySupport: false,
      exportToPdf: false,
    },
    isActive: true,
    sortOrder: 1,
  },
  {
    id: '2',
    name: 'Basic',
    price: '99000',
    yearlyPrice: '990000',
    billingCycle: 'MONTHLY' as const,
    features: {
      maxRecipeGenerations: 20,
      maxVideoGenerations: 5,
      maxCommunityPosts: 10,
      maxCommunityComments: 50,
      premiumTemplates: true,
      aiSuggestions: true,
      prioritySupport: false,
      exportToPdf: true,
    },
    isActive: true,
    sortOrder: 2,
  },
  {
    id: '3',
    name: 'Pro',
    price: '199000',
    yearlyPrice: '1990000',
    billingCycle: 'MONTHLY' as const,
    features: {
      maxRecipeGenerations: -1,
      maxVideoGenerations: -1,
      maxCommunityPosts: -1,
      maxCommunityComments: -1,
      premiumTemplates: true,
      aiSuggestions: true,
      prioritySupport: true,
      exportToPdf: true,
    },
    isActive: true,
    sortOrder: 3,
  },
];

export const mockUserSubscription = {
  id: '1',
  planId: '1',
  status: 'ACTIVE' as const,
  startDate: new Date().toISOString(),
  billingCycle: 'MONTHLY' as const,
  autoRenew: true,
  plan: mockSubscriptionPlans[0],
  usageQuota: {
    recipeGenerationsLeft: 5,
    videoGenerationsLeft: 1,
    communityPostsLeft: 3,
  },
};

// Mock users data
export const mockUsers = [
  {
    id: '1',
    email: 'admin@example.com',
    firstName: 'Admin',
    lastName: 'User',
    role: 'ADMIN',
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(), // 30 days ago
  },
  {
    id: '2',
    email: 'john@example.com',
    firstName: 'John',
    lastName: 'Doe',
    role: 'MEMBER',
    isActive: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(), // 15 days ago
  },
  {
    id: '3',
    email: 'jane@example.com',
    firstName: 'Jane',
    lastName: 'Smith',
    role: 'MODERATOR',
    isActive: true,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), // 7 days ago
  },
  {
    id: '4',
    email: 'inactive@example.com',
    firstName: 'Inactive',
    lastName: 'User',
    role: 'MEMBER',
    isActive: false,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(), // 60 days ago
  },
];

// Mock recipes data
export const mockRecipes = [
  {
    id: '1',
    title: 'Phở Bò Truyền Thống',
    description: 'Món phở bò đậm đà với nước dùng được ninh từ xương bò trong nhiều giờ',
    ingredients: ['Bánh phở', 'Thịt bò', 'Hành tây', 'Gừng', 'Quế', 'Hồi', 'Đinh hương'],
    instructions: [
      'Chuẩn bị xương bò và thịt bò',
      'Ninh nước dùng với gia vị trong 8 tiếng',
      'Chuẩn bị bánh phở và rau ăn kèm',
      'Trình bày và thưởng thức'
    ],
    cuisine: 'Vietnamese',
    difficulty: 'Hard',
    prepTime: 30,
    cookTime: 480, // 8 hours
    servings: 4,
    createdByAI: false,
    author: { firstName: 'Chef', lastName: 'Vietnam' },
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    isFlagged: false,
    isApproved: true,
    likes: 125,
    comments: 23,
  },
  {
    id: '2',
    title: 'AI-Generated Pasta Carbonara',
    description: 'Classic Italian pasta dish generated by AI with authentic flavors',
    ingredients: ['Spaghetti', 'Eggs', 'Pecorino Romano', 'Guanciale', 'Black pepper'],
    instructions: [
      'Cook pasta in salted water',
      'Render guanciale until crispy',
      'Mix eggs with cheese',
      'Combine everything off heat'
    ],
    cuisine: 'Italian',
    difficulty: 'Medium',
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    createdByAI: true,
    author: { firstName: 'AI', lastName: 'Chef' },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    isFlagged: true,
    isApproved: false,
    likes: 89,
    comments: 12,
  },
  {
    id: '3',
    title: 'Healthy Green Smoothie',
    description: 'Nutritious green smoothie perfect for breakfast or post-workout',
    ingredients: ['Spinach', 'Banana', 'Apple', 'Lemon juice', 'Ginger', 'Water'],
    instructions: [
      'Wash all ingredients thoroughly',
      'Add ingredients to blender',
      'Blend until smooth',
      'Serve immediately'
    ],
    cuisine: 'International',
    difficulty: 'Easy',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    createdByAI: false,
    author: { firstName: 'Health', lastName: 'Guru' },
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isFlagged: false,
    isApproved: true,
    likes: 67,
    comments: 8,
  },
];

// Mock comments data
export const mockComments = [
  {
    id: '1',
    recipeId: '1',
    userId: '2',
    author: { firstName: 'John', lastName: 'Doe' },
    content: 'Amazing recipe! The broth was so flavorful.',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    isFlagged: false,
    likes: 5,
  },
  {
    id: '2',
    recipeId: '2',
    userId: '3',
    author: { firstName: 'Jane', lastName: 'Smith' },
    content: 'This seems inappropriate for a cooking site.',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    isFlagged: true,
    likes: 0,
  },
];

// Mock dashboard metrics
export const mockDashboardMetrics = {
  totalUsers: 1234,
  totalRecipes: 5678,
  totalComments: 9876,
  activeSubscriptions: 234,
  totalRevenue: 12500000, // in VND
  newUsersThisMonth: 156,
  newRecipesThisMonth: 89,
  flaggedContent: 12,
  systemLoad: 65, // percentage
  errorRate: 0.02, // 2%
};

// Mock user analytics
export const mockUserAnalytics = {
  totalUsers: 1234,
  activeUsers: 892,
  newUsers: 156,
  usersByRole: {
    ADMIN: 5,
    MODERATOR: 15,
    MEMBER: 1214,
  },
  userGrowth: [
    { date: '2024-01-01', count: 1000 },
    { date: '2024-01-02', count: 1025 },
    { date: '2024-01-03', count: 1050 },
    { date: '2024-01-04', count: 1080 },
    { date: '2024-01-05', count: 1120 },
    { date: '2024-01-06', count: 1150 },
    { date: '2024-01-07', count: 1234 },
  ],
  registrationsByDay: [
    { day: 'Monday', count: 25 },
    { day: 'Tuesday', count: 32 },
    { day: 'Wednesday', count: 28 },
    { day: 'Thursday', count: 35 },
    { day: 'Friday', count: 42 },
    { day: 'Saturday', count: 38 },
    { day: 'Sunday', count: 30 },
  ],
};

// Mock recipe analytics
export const mockRecipeAnalytics = {
  totalRecipes: 5678,
  publishedRecipes: 5234,
  draftRecipes: 344,
  flaggedRecipes: 100,
  aiGeneratedRecipes: 2100,
  userCreatedRecipes: 3578,
  recipesByDifficulty: {
    Easy: 2500,
    Medium: 2178,
    Hard: 1000,
  },
  recipesByCuisine: {
    Vietnamese: 1500,
    Italian: 1200,
    Chinese: 900,
    Japanese: 800,
    American: 600,
    French: 400,
    Other: 278,
  },
  popularRecipes: [
    { id: '1', title: 'Phở Bò Truyền Thống', views: 15000, likes: 1250 },
    { id: '2', title: 'Bánh Mì Thịt Nướng', views: 12500, likes: 980 },
    { id: '3', title: 'Cơm Tấm Sườn Nướng', views: 11200, likes: 890 },
  ],
};

// Mock engagement analytics
export const mockEngagementAnalytics = {
  totalLikes: 125000,
  totalComments: 45000,
  totalShares: 12000,
  averageEngagementRate: 8.5, // percentage
  engagementByContent: {
    recipes: 80000,
    comments: 35000,
    profiles: 10000,
  },
  engagementTrend: [
    { date: '2024-01-01', likes: 1200, comments: 450, shares: 120 },
    { date: '2024-01-02', likes: 1350, comments: 520, shares: 140 },
    { date: '2024-01-03', likes: 1180, comments: 480, shares: 110 },
    { date: '2024-01-04', likes: 1420, comments: 580, shares: 160 },
    { date: '2024-01-05', likes: 1650, comments: 640, shares: 180 },
    { date: '2024-01-06', likes: 1500, comments: 590, shares: 150 },
    { date: '2024-01-07', likes: 1800, comments: 720, shares: 200 },
  ],
  topEngagedUsers: [
    { id: '2', name: 'John Doe', totalEngagement: 2500 },
    { id: '3', name: 'Jane Smith', totalEngagement: 2200 },
    { id: '4', name: 'Bob Johnson', totalEngagement: 1800 },
  ],
};

// Mock system health
export const mockSystemHealth = {
  status: 'healthy',
  uptime: 99.9,
  responseTime: 120, // milliseconds
  cpuUsage: 45.2,
  memoryUsage: 67.8,
  diskUsage: 34.5,
  databaseConnections: 25,
  cacheHitRate: 94.5,
  errorRate: 0.02,
  activeUsers: 234,
  requestsPerMinute: 1250,
  services: {
    api: { status: 'healthy', responseTime: 95 },
    database: { status: 'healthy', responseTime: 15 },
    cache: { status: 'healthy', responseTime: 2 },
    storage: { status: 'healthy', responseTime: 45 },
  },
  alerts: [
    {
      id: '1',
      type: 'warning',
      message: 'Memory usage above 60%',
      timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
    {
      id: '2',
      type: 'info',
      message: 'Scheduled maintenance completed',
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    },
  ],
};

// Check if we're in development mode
export const isDevelopmentMode = () => {
  // Check if dev banner is explicitly enabled
  const showDevBanner = import.meta.env.VITE_SHOW_DEV_BANNER === 'true';
  if (!showDevBanner) return false;
  
  return import.meta.env.DEV && !import.meta.env.VITE_API_URL?.includes('production');
};
